### ISSUE TITLE
run sample

### ISSUE THREAD

**Issue by enigmista91** [kthouz/NYC_Green_Taxi#1] opened 2017-06-27 21:02 UTC
Hi which is a sample to tun the tip_predictor.make_predictions ("data_september_2015.csv") because this command not work

**Comment by kthouz** [comment] 2017-06-27 21:20
Can you post the error that is being printed?

**Comment by enigmista91** [comment] 2017-06-28 13:51
tip_predictor.make_predictions(data_september_2015.csv)
-bash: syntax error near unexpected token `data_september_2015.csv'

If I try to run the sample I obtain that.

I have, also answer how much memory ram I need to run all experiment?

**Comment by kthouz** [comment] 2017-07-01 03:19
tip_predictor.make_predictions(data) works only inside python. 

I added a new script, [predict_tips.py](https://github.com/kthouz/NYC_Green_Taxi/blob/master/predict_tips.py), that can help you to issue that  command on your terminal.

Just run your command as
`$python predict_tips.py dataset.csv`

**Comment by enigmista91** [comment] 2017-07-02 17:10
ok, many thanks.
I fix some other problem over you suggest, but despite I have installed shapely I obtain

 python tip_predictor.py data_september_2015.csv
Traceback (most recent call last):
  File "tip_predictor.py", line 23, in <module>
    from shapely.geometry import Point,Polygon,MultiPoint,MultiPolygon
ImportError: No module named 'shapely' 

Have you any idea?

Many thanks

**Comment by kthouz** [comment] 2017-07-02 17:28
1. Regarding shapely, it appears that it didn't install properly since python is unable to locate it. A quick check is to run `from shapely.geometry import Point` in you python and see if this doesn't produce an error.

2. I think you are using a wrong script. I pushed a new script called predict_tips.py. You can download it or just cd to you directory and run `$git pull` to synchronize to the most recent update. Then run `$python predict_tips.py dataset.csv`

**Comment by enigmista91** [comment] 2017-07-02 21:01
ok, many thanks now the script go and I find why it ask shapely, and the sciprt didn't see shapely.

But when the script run don't find  my_regressor.pkl, I control the repository but there isn't. Where can I find? or make this file?

**Comment by kthouz** [comment] 2017-07-03 00:17
Sorry for that. my_regressor.pkl is a pickle of the pre-trained regression model. It is 99MB bigger than github recommended size. I just pushed [it](https://github.com/kthouz/NYC_Green_Taxi/blob/master/my_regressor.pkl). You can download it in the root directory of the repo.

**Comment by enigmista91** [comment] 2017-07-03 09:44
many thanks I try immediately

**Comment by kthouz** [comment] 2017-07-04 04:40
let me know it goes and feel free to close the issue if you are all set

**Comment by enigmista91** [comment] 2017-07-05 19:58
I'm sorry for my delay.

I have the last question:
at the finish the esecution (phase predtict) the console said  "submissions and cleaned data saved as submission.csv and cleaned_data.csv respectively
run evaluate_predictions() to compare them"

But I don't understand how can I run this method

Many thanks for the help

**Comment by enigmista91** [comment] 2017-07-05 20:00
I try  python tip_predictor.evalute_predictions()
but ... -bash: syntax error near unexpected token `('

**Comment by enigmista91** [comment] 2017-07-05 20:11
python -c 'from tip_predictor  import *; print evaluate_predictions() '

I solved now the method go to end

**Comment by kthouz** [comment] 2017-07-05 20:44
Awesome.
Good luck with the project you are working on.
For now, am gonna close the issue but feel free to re-open it if you still need any support

**Closed as completed by kthouz** 2017-07-05 20:44 UTC
